nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:3000']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization']
  paths:
    '^/':   # <-- чтобы работало ДЛЯ ВСЕХ РОУТОВ
      allow_origin: ['http://localhost:3000']
      allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
      allow_headers: ['Content-Type', 'Authorization']
